modLoader="javafml"
#loaderVersion="[${loader_version},)"
license="GPLv3"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/TesseractAPI/issues"

[[mods]]
modId="tesseract"
#version="${version}"
version="0.0.1"
displayName="TesseractAPI"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GregTech-Intergalactical/TesseractAPI"
#logoFile="examplemod.png"
authors="coderbot16, qubka, repolainen, mitchej123, Muramasa"
description='''Powerful framework for energy, item, and fluid transport'''
[[dependencies.tesseract]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tesseract]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"